name: spring-framework-petclinic
on:
  push:
    branches: 
      - master
env:
  ENV: Dev	
  #DATE: date -u +"%Y%m%d" 
jobs:
  checkout:
    runs-on: aws
    steps:
    - name: checkout
      uses: actions/checkout@v4
  sonarQubeTrigger:
    runs-on: aws
    steps:
    - name: Run SonarQube analysis with Maven
      run: |
        mvn clean verify sonar:sonar 
         -Dsonar.projectKey=spring-framework-petclinic 
         -Dsonar.host.url=${{ secrets.HOST_URL }} 
         -Dsonar.token=${{ secrets.SONAR_TOKEN }}
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
