name: spring-framework-petclinic
on:
  push:
    branches: 
      - master
env:
  ENV: Dev	
  #DATE: date -u +"%Y%m%d" 
jobs:
  checkout:
    runs-on: aws
    steps:
    - name: checkout
      uses: actions/checkout@v4
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2
      with:
        projectBaseDir: .
        args: "-Dsonar.projectKey=spring-framework-petclinic -Dsonar.host.url=${{ secrets.HOST_URL }}"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
